// Actions
export const UPDATE_GRAPHQL_ERRORS = 'UPDATE_GRAPHQL_ERRORS';
export const RESET_GRAPHQL_ERRORS = 'RESET_GRAPHQL_ERRORS';
export const UPDATE_MINER_ACTION = 'UPDATE_MINER_ACTION';
export const RESET_MINER_ACTION = 'RESET_MINER_ACTION';
export const UPDATE_NODE_STATS = 'UPDATE_NODE_STATS';
export const UPDATE_MINER_STATS = 'UPDATE_MINER_STATS';
export const UPDATE_MCU_STATS = 'UPDATE_MCU_STATS';