// Actions
export const SEND_FEEDBACK = 'SEND_FEEDBACK';
export const RESET_FEEDBACK = 'RESET_FEEDBACK';
export const UPDATE_MINER_ACTION = 'UPDATE_MINER_ACTION';
export const RESET_MINER_ACTION = 'RESET_MINER_ACTION';
export const UPDATE_NODE_STATS = 'UPDATE_NODE_STATS';
export const UPDATE_MINER_STATS = 'UPDATE_MINER_STATS';
export const UPDATE_MCU_STATS = 'UPDATE_MCU_STATS';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_WIFI = 'UPDATE_WIFI';