const initialState = {
  Node: {
    stats: {
      result: {
        stats: {
          timestamp: null,
          blockchainInfo: {
            blocks: null,
            blockTime: null,
            headers: null,
            sizeOnDisk: null,
            verificationprogress: null,
          },
          connectionCount: null,
          miningInfo: {
            difficulty: null,
            networkhashps: null,
          },
          peerInfo: [],
          networkInfo: {
            version: null,
            subversion: null,
            localaddresses: [],
            connections_in: null,
            connections_out: null,
          },
          error: null,
          __typename: 'NodeStats',
        },
        __typename: 'NodeStatsResult',
      },
      error: null,
      __typename: 'NodeStatsOutput',
    },
    __typename: 'NodeActions',
  },
  Mcu: {
    stats: {
      result: {
        stats: {
          timestamp: null,
          hostname: null,
          operatingSystem: null,
          uptime: null,
          loadAverage: null,
          architecture: null,
          temperature: null,
          minerTemperature: null,
          minerFanSpeed: null,
          activeWifi: null,
          bfgminerLog: null,
          network: null,
          memory: {
            total: null,
            available: null,
            used: null,
            cache: null,
            __typename: 'MemoryStats',
          },
          cpu: {
            threads: null,
            usedPercent: null,
            __typename: 'CpuStats',
          },
          disks: [],
          __typename: 'McuStats',
        },
        __typename: 'McuStatsResult',
      },
      error: null,
      __typename: 'McuStatsOutput',
    },
    __typename: 'McuActions',
  },
  Miner: {
    stats: {
      result: {
        stats: [
          {
            uuid: null,
            version: null,
            date: null,
            statVersion: null,
            comport: null,
            versions: {
              miner: null,
              minerDate: null,
              minerDebug: null,
              mspVer: null,
              __typename: 'MinerStatsVersion',
            },
            master: {
              upTime: null,
              diff: null,
              boards: null,
              errorSpi: null,
              osc: null,
              hwAddr: null,
              boardsI: null,
              boardsW: null,
              wattPerGHs: null,
              intervals: {
                int_0: {
                  name: 'total',
                  interval: null,
                  bySol: null,
                  byDiff: null,
                  byPool: null,
                  byJobs: null,
                  solutions: null,
                  errors: null,
                  errorRate: null,
                  chipSpeed: null,
                  chipRestarts: null,
                  __typename: 'MinerStatsMasterInterval',
                },
                int_30: {
                  name: '30 sec',
                  interval: null,
                  bySol: null,
                  byDiff: null,
                  byPool: null,
                  byJobs: null,
                  solutions: null,
                  errors: null,
                  errorRate: null,
                  chipSpeed: null,
                  chipRestarts: null,
                  __typename: 'MinerStatsMasterInterval',
                },
                int_300: {
                  name: '5 min',
                  interval: null,
                  bySol: null,
                  byDiff: null,
                  byPool: null,
                  byJobs: null,
                  solutions: null,
                  errors: null,
                  errorRate: null,
                  chipSpeed: null,
                  chipRestarts: null,
                  __typename: 'MinerStatsMasterInterval',
                },
                int_900: {
                  name: '15 min',
                  interval: null,
                  bySol: null,
                  byDiff: null,
                  byPool: null,
                  byJobs: null,
                  solutions: null,
                  errors: null,
                  errorRate: null,
                  chipSpeed: null,
                  chipRestarts: null,
                  __typename: 'MinerStatsMasterInterval',
                },
                int_3600: {
                  name: '1 hour',
                  interval: null,
                  bySol: null,
                  byDiff: null,
                  byPool: null,
                  byJobs: null,
                  solutions: null,
                  errors: null,
                  errorRate: null,
                  chipSpeed: null,
                  chipRestarts: null,
                  __typename: 'MinerStatsMasterInterval',
                },
                __typename: 'MinerStatsMasterIntervals',
              },
              __typename: 'MinerStatsMaster',
            },
            pool: {
              host: null,
              port: null,
              userName: null,
              diff: null,
              intervals: {
                int_0: {
                  name: 'total',
                  interval: null,
                  jobs: null,
                  cleanFlags: null,
                  sharesSent: null,
                  sharesAccepted: null,
                  sharesRejected: null,
                  solutionsAccepted: null,
                  minRespTime: null,
                  avgRespTime: null,
                  maxRespTime: null,
                  shareLoss: null,
                  poolTotal: null,
                  inService: null,
                  subscribeError: null,
                  diffChanges: null,
                  reconnections: null,
                  reconnectionsOnErrors: null,
                  defaultJobShares: null,
                  staleJobShares: null,
                  duplicateShares: null,
                  lowDifficultyShares: null,
                  pwcSharesSent: null,
                  pwcSharesDropped: null,
                  bigDiffShares: null,
                  belowTargetShare: null,
                  pwcRestart: null,
                  statOverflow: null,
                  __typename: 'MinerStatsPoolInterval',
                },
                __typename: 'MinerStatsPoolIntervals',
              },
              __typename: 'MinerStatsPool',
            },
            fans: {
              int_0: {
                rpm: [],
                __typename: 'MinerStatsFan',
              },
              __typename: 'MinerStatsFans',
            },
            temperature: {
              count: null,
              min: null,
              avr: null,
              max: null,
              __typename: 'MinerStatsTemperature',
            },
            slots: {
              int_0: {
                revision: null,
                spiNum: null,
                spiLen: null,
                pwrNum: null,
                pwrLen: null,
                btcNum: null,
                specVoltage: null,
                chips: null,
                pwrOn: null,
                pwrOnTarget: null,
                revAdc: null,
                temperature: null,
                temperature1: null,
                ocp: null,
                heaterErr: null,
                heaterErrNum: null,
                inOHOsc: null,
                ohOscNum: null,
                ohOscTime: null,
                overheats: null,
                overheatsTime: null,
                lowCurrRst: null,
                currents: [],
                brokenPwc: null,
                solutions: null,
                errors: null,
                ghs: null,
                errorRate: null,
                chipRestarts: null,
                wattPerGHs: null,
                tmpAlert: [
                  {
                    alertLo: null,
                    alertHi: null,
                    numWrite: null,
                    __typename: 'MinerStatsSlotAlert',
                  },
                  {
                    alertLo: null,
                    alertHi: null,
                    numWrite: null,
                    __typename: 'MinerStatsSlotAlert',
                  },
                ],
                osc: null,
                oscStopChip: null,
                __typename: 'MinerStatsSlot',
              },
              __typename: 'MinerStatsSlots',
            },
            slaves: [
              {
                id: null,
                uid: null,
                ver: null,
                rx: null,
                err: null,
                time: null,
                ping: null,
                __typename: 'MinerStatsSlave',
              },
            ],

            __typename: 'MinerStats',
          },
        ],
        __typename: 'MinerStatsResult',
      },
      error: null,
      __typename: 'MinerStatsOutput',
    },
    online: {
      result: {
        online: {
          timestamp: null,
          status: null,
          __typename: 'MinerOnline',
        },
        __typename: 'MinerOnlineResult',
      },
      error: null,
      __typename: 'MinerOnlineOutput',
    },
    __typename: 'MinerActions',
  },
};

export default initialState;
